export const patentData = [
  {
    topic: "이동 로봇들의 결합을 위한 도킹 시스템 및 방법",
    inventor: "김용태 문용필 정진우",
    publication_type: "patent",
    filling_no: "10-2008-0126596",
    filling_date: "2008.12.12",
    granted_no: "10-0915801",
    granted_date: "2009.8.31",
    progress: "기술이전",
  },
  {
    topic:
      "공간 메커니즘을 이용한 이동로봇과 이를 이용한 이동로봇 협동 제어 시스템 및 방법",
    inventor: "정진우",
    publication_type: "patent",
    filling_no: "10-2009-0096704",
    filling_date: "2009.10.12",
    granted_no: "10-1000879",
    granted_date: "2010.12.7",
    progress: "기술이전",
  },
  {
    topic: "다단계 형태 공간을 이용한 이동 경로 계획 방법 및 장치",
    inventor: "정진우 소병철",
    publication_type: "patent",
    filling_no: "10-2010-0040911",
    filling_date: "2010.4.30",
    granted_no: "10-1213632",
    granted_date: "2012.12.12",
    progress: "기술이전",
  },
  {
    topic: "이동체(mobile body)를 위한 셀―기반 경로 계획 장치 및 방법",
    inventor: "정진우 소병철",
    publication_type: "patent",
    filling_no: "10-2011-0017375",
    filling_date: "2011.2.25",
    granted_no: "10-1203987",
    granted_date: "2012.11.16",
    progress: "기술이전",
  },
  {
    topic: "로봇위치 및 동작 측정방법, 로봇위치 및 동작 측정 장치",
    inventor: "정진우 조영원 소병철 박정수",
    publication_type: "patent",
    filling_no: "10-2011-0090892",
    filling_date: "2011.9.7",
    granted_no: "10-1314176",
    granted_date: "2013.9.26",
    progress: "기술이전",
  },
  {
    topic: "텍스트로부터 애니메이션을 생성하는 방법 및 장치",
    inventor: "정진우 조영원 소병철 박정수",
    publication_type: "patent",
    filling_no: "10-2011-0123110",
    filling_date: "2011.11.23",
    granted_no: "10-1348282",
    granted_date: "2013.12.30",
    progress: "등록",
  },
  {
    topic: "APPARATUS AND METHOD OF CELL-BASED PATH PLANNING FOR MOBILE BODY",
    inventor: "정진우 소병철",
    publication_type: "patent",
    filling_no: "13/303,620",
    filling_date: "2011.11.30",
    granted_no: "9116523",
    granted_date: "2015.10.28",
    progress: "등록",
    note: "International",
  },
  {
    topic:
      "기준점이 불확실한 저해상도 이미지의 중심점 및 회전각도 조정방법 및 조정장치",
    inventor: "정진우 조영원 소병철",
    publication_type: "patent",
    filling_no: "10-2012-0066187",
    filling_date: "2012.6.20",
    granted_no: "10-1402063",
    granted_date: "2014.5.25",
    progress: "등록",
  },
  {
    topic: "발자국 에너지 이미지를 이용한 사용자 인식방법 및 그 장치",
    inventor: "정진우 조영원 소병철",
    publication_type: "patent",
    filling_no: "10-2012-0066188",
    filling_date: "2012.6.20",
    granted_no: "10-1436884",
    granted_date: "2014.8.27",
    progress: "등록",
  },
  {
    topic: "신발 발자국 이미지를 이용한 사용자 인식방법 및 그 장치",
    inventor: "정진우 조영원 소병철",
    publication_type: "patent",
    filling_no: "10-2012-0066189",
    filling_date: "2012.6.20",
    granted_no: "10-1288949",
    granted_date: "2013.7.17",
    progress: "등록",
  },
  {
    topic: "회화적 표현을 위한 영상 처리 장치 및 방법",
    inventor: "정진우 조영원 나종원",
    publication_type: "patent",
    filling_no: "10-2013-0010611",
    filling_date: "2013.1.30",
    granted_no: "10-1406861",
    granted_date: "2014.6.5",
    progress: "등록",
  },
  {
    topic:
      "텍스트로부터 애니메이션을 생성하는 방법 및 장치 와 청각장애인의 기본모음 조음 훈련을 돕기위한 소프트웨어형 보조로봇에 관현 연구를 통한 기술노하우를 이용한 증강현실 기반의 음성인식 3D 교육컨텐츠 개발",
    inventor: "정진우",
    publication_type: "patent",
    filling_no: "",
    filling_date: "",
    granted_no: "",
    granted_date: "",
    progress: "노하우이전",
  },
  {
    topic: "손 검출 장치 및 방법",
    inventor: "정진우 조영원 장윤희",
    publication_type: "patent",
    filling_no: "10-2014-0010311",
    filling_date: "2014.1.28",
    granted_no: "10-1528417",
    granted_date: "2015.6.5",
    progress: "기술이전",
  },
  {
    topic: "지자계 센서를 이용한 실내 위치 추적 시스템",
    inventor: "정진우 황다솜 김예슬 김태현",
    publication_type: "patent",
    filling_no: "10-2014-0009891",
    filling_date: "2014.1.27",
    granted_no: "",
    granted_date: "",
    progress: "출원",
  },
  {
    topic: "수화 인식을 통한 문장 자동 완성 시스템 및 방법",
    inventor: "정진우 김종성 정제영 김형준 최유선",
    publication_type: "patent",
    filling_no: "10-2014-0009892",
    filling_date: "2014.1.27",
    granted_no: "",
    granted_date: "",
    progress: "출원",
  },
  {
    topic: "청각 장애인과 건청인 모두를 위한 수화 사전 장치",
    inventor: "정진우 김태원 김미림 김유진 차지정",
    publication_type: "patent",
    filling_no: "10-2014-0009893",
    filling_date: "2014.1.27",
    granted_no: "",
    granted_date: "",
    progress: "출원",
  },
  {
    topic: "증강현실을 이용한 모바일 교육 콘텐츠 개발",
    inventor: "정진우",
    publication_type: "patent",
    filling_no: "",
    filling_date: "",
    granted_no: "",
    granted_date: "",
    progress: "노하우이전",
  },
  {
    topic: "로봇 시스템 및 그의 제어 방법",
    inventor: "정진우 손윤식",
    publication_type: "patent",
    filling_no: "10-2015-0161180",
    filling_date: "2015.11.17",
    granted_no: "10-1769513",
    granted_date: "2017.8.11",
    progress: "등록",
  },
  {
    topic: "화장품 추천 및 테스팅 시스템",
    inventor: "정진우 한려령 유건이 박종민 왕인정 이윤정",
    publication_type: "patent",
    filling_no: "",
    filling_date: "2015.11.12",
    granted_no: "",
    granted_date: "2016.2.25",
    progress: "소프트웨어등록",
  },
  {
    topic: "핀테크를 이용한 주차정산 프로그램",
    inventor: "정진우 김기남 서영민 김지영 황선아",
    publication_type: "patent",
    filling_no: "",
    filling_date: "2015.11.12",
    granted_no: "",
    granted_date: "2016.3.16",
    progress: "소프트웨어등록",
  },
  {
    topic: "온라인 화장품 추전방법",
    inventor: "정진우 한려령 유건이 박종민 왕인정 이윤정",
    publication_type: "patent",
    filling_no: "10-2016-0006527",
    filling_date: "2016.1.19",
    granted_no: "",
    granted_date: "",
    progress: "출원",
  },
  {
    topic:
      "비콘을 이용한 주차관리서버, 이를 포함하는 주차관리시스템 및 주차관리 방법",
    inventor: "정진우 김기남 서영민 김지영 황선아",
    publication_type: "patent",
    filling_no: "10-2016-0006551",
    filling_date: "2016.1.19",
    granted_no: "",
    granted_date: "",
    progress: "출원",
  },
  {
    topic: "소프트웨어 품질 시각화 장치 및 방법",
    inventor: "정진우 이재경 홍성호 박현민 손대근",
    publication_type: "patent",
    filling_no: "10-2016-0167074",
    filling_date: "2016.12.8",
    granted_no: "10-1940538",
    granted_date: "2019.1.15",
    progress: "등록",
  },
  {
    topic: "질의에 대한 응답 생성 장치 및 방법",
    inventor: "정진우 김준규 조양규 김수희 양기",
    publication_type: "patent",
    filling_no: "10-2016-0168843",
    filling_date: "2016.12.12",
    granted_no: "10-1832816",
    granted_date: "2018.2.21",
    progress: "등록",
  },
  {
    topic: "소프트웨어 품질 시각화 장치 및 방법",
    inventor: "정진우 이재경 홍성호 박현민 손대근",
    publication_type: "patent",
    filling_no: "",
    filling_date: "2016.11.8",
    granted_no: "",
    granted_date: "2016.12.12",
    progress: "소프트웨어등록",
  },
  {
    topic: "리버스 카메라",
    inventor: "정진우 이재경",
    publication_type: "patent",
    filling_no: "",
    filling_date: "2016.8.31",
    granted_no: "",
    granted_date: "2017.1.10",
    progress: "소프트웨어등록",
  },
  {
    topic: "무선 공유기 및 이를 이용한 사용자별 선별적 웹사이트 접속 차단 방법",
    inventor: "정진우 안성현 김가림 김용현 정한솔",
    publication_type: "patent",
    filling_no: "10-2017-0181108",
    filling_date: "2017.12.27",
    granted_no: "10-2039959",
    granted_date: "2019.10.29",
    progress: "등록",
  },
  {
    topic: "전자드럼",
    inventor: "정진우 박승현 김재훈 김하연 안수길",
    publication_type: "patent",
    filling_no: "10-2017-0181109",
    filling_date: "2017.12.27",
    granted_no: "10-2013944",
    granted_date: "2019.8.19",
    progress: "등록",
  },
  {
    topic: "이메일 보안 관리 시스템",
    inventor: "정진우 조현준 윤태연 김일엽 임윤미",
    publication_type: "patent",
    filling_no: "10-2018-0041595",
    filling_date: "2018.4.10",
    granted_no: "",
    granted_date: "",
    progress: "출원",
  },
  {
    topic: "정보화 자막 방법 및 이를 수행하기 위한 장치",
    inventor: "정진우 손윤식 최용식",
    publication_type: "patent",
    filling_no: "10-2017-0163803",
    filling_date: "2017.11.30",
    granted_no: "",
    granted_date: "",
    progress: "출원",
  },
  {
    topic: "단일 카메라 기반 굴삭기 버켓 내 토사물 체적 산출 방법",
    inventor: "정진우 김인환 임동우",
    publication_type: "patent",
    filling_no: "10-2018-0085800",
    filling_date: "2018.7.24",
    granted_no: "10-2034281",
    granted_date: "2019.10.14",
    progress: "등록",
  },
  {
    topic: "안전 운전을 유도하는 운전자 편의 장치",
    inventor: "정진우 이승훈 김민우",
    publication_type: "patent",
    filling_no: "10-2018-0004526",
    filling_date: "2018.1.12",
    granted_no: "",
    granted_date: "",
    progress: "출원",
  },
  {
    topic: "모션인식 기반의 홀로그램 출력 전자칠판",
    inventor: "정진우 원가연 김민우 박지용 김강산",
    publication_type: "patent",
    filling_no: "10-2018-0172333",
    filling_date: "2018.12.28",
    granted_no: "",
    granted_date: "",
    progress: "출원",
  },
  {
    topic: "동영상 오버랩 출력 제어 방법",
    inventor: "정진우 이상용 서다솔 김성탁 김연준",
    publication_type: "patent",
    filling_no: "10-2019-0178709",
    filling_date: "2019.12.30",
    granted_no: "10-2263412",
    granted_date: "2021.6.4",
    progress: "등록",
  },
  {
    topic: "실시간 암호화폐 거래 내역 제공 방법",
    inventor: "정진우 홍승준 박정진 이채은 류하영",
    publication_type: "patent",
    filling_no: "10-2019-0178705",
    filling_date: "2019.12.30",
    granted_no: "",
    granted_date: "",
    progress: "출원",
  },
  {
    topic: "영상분석을 통한 상황 인식 기반 강의실 조명 제어 시스템",
    inventor: "정진우 황석범 김연진 김강일 김민지",
    publication_type: "patent",
    filling_no: "10-2019-0178704",
    filling_date: "2019.12.30",
    granted_no: "",
    granted_date: "",
    progress: "출원",
  },
  {
    topic: "블럭형 모듈 적층 구조를 갖는 IoT 커스터마이징 디바이스",
    inventor: "정진우 최정근 이재연 홍사민",
    publication_type: "patent",
    filling_no: "10-2019-0178703",
    filling_date: "2019.12.30",
    granted_no: "",
    granted_date: "",
    progress: "출원",
  },
  {
    topic:
      "게임 요소와 게임 컨텐츠 소모 시간과의 연관성 정량화를 통한 게임 난이도 조절 방법",
    inventor: "정진우 홍사민 최정근 이재연",
    publication_type: "patent",
    filling_no: "10-2019-0178702",
    filling_date: "2019.12.30",
    granted_no: "",
    granted_date: "",
    progress: "출원",
  },
  {
    topic: "스마트 추종체를 위한 뒤태 기반 사용자 인식 시스템 및 방법",
    inventor: "정진우 최용식 양승윤 김승주 강진구",
    publication_type: "patent",
    filling_no: "10-2020-0178610",
    filling_date: "2020.12.18",
    granted_no: "",
    granted_date: "",
    progress: "출원",
  },
  {
    topic: "레이저 거리 측정기를 이용한 투명 장애물 인식 방법 및 장치",
    inventor: "정진우 최용식 강진구 박정수 강태원",
    publication_type: "patent",
    filling_no: "10-2020-0178611",
    filling_date: "2020.12.18",
    granted_no: "",
    granted_date: "",
    progress: "출원",
  },
  {
    topic: "신경망 기반 디지털 문서의 위아래 방향 판단 장치 및 방법",
    inventor: "정진우 신예지 강진구 최용식 김지훈",
    publication_type: "patent",
    filling_no: "10-2020-0178612",
    filling_date: "2020.12.18",
    granted_no: "",
    granted_date: "",
    progress: "출원",
  },
  {
    topic:
      "다양한 PCB 회로에서 MRRF를 이용하여 공극을 검출하기 위한 영상 처리 시스템",
    inventor: "정진우 김경민 김인제 박재현 채현욱",
    publication_type: "patent",
    filling_no: "10-2020-0175269",
    filling_date: "",
    granted_no: "",
    granted_date: "",
    progress: "출원",
  },
  {
    topic: "영상 내 프라이버시 영역 비식별화 및 복원 시스템",
    inventor: "정진우",
    publication_type: "patent",
    filling_no: "",
    filling_date: "",
    granted_no: "",
    granted_date: "",
    progress: "노하우이전",
  },
  {
    topic:
      "프라이버시 영역 비식별화 및 복원 장치, 프라이버시 영역 비식별화 및 복원 방법",
    inventor: "정진우 양승윤",
    publication_type: "patent",
    filling_no: "10-2021-0156904",
    filling_date: "2021.11.15",
    granted_no: "",
    granted_date: "",
    progress: "출원",
  },
  {
    topic: "위치 추정 장치 및 방법",
    inventor: "정진우 강태원",
    publication_type: "patent",
    filling_no: "10-2021-0149442",
    filling_date: "2021.11.3",
    granted_no: "",
    granted_date: "",
    progress: "출원",
  },
  {
    topic: "삼각부등식을 이용한 샘플링 기반 경로 계획 방법",
    inventor: "정진우 강진구 강태원 최용식",
    publication_type: "patent",
    filling_no: "10-2021-0158059",
    filling_date: "2021.11.16",
    granted_no: "",
    granted_date: "",
    progress: "출원",
  },
];
